[RAT-27] changes from the branch
digitalhps/digitalhps.org pull request #5
Opened 2024-11-19 17:17 UTC by Warrior1412

2024-11-19 18:49 UTC, jdamerow commented
- On the Consoritium > news & updates page (news-updates.html) are still login links
- everything in the "user" folder should not be needed anymore?
- the warning on the hps repository page isn't there

2024-11-21 15:24 UTC, Warrior1412 commented
[RAT-27] removed login from news-updates.html, removed contents in "user" folder should, warning on the hps repository

2024-11-21 15:35 UTC, jdamerow requested changes
And the login links are still there
![image](https://github.com/user-attachments/assets/de3a5e0f-c889-4c35-aa43-0803e6fa835b)

2024-11-21 15:35 UTC, jdamerow commented on node/3.html
> +    <div class="field field-name-body field-type-text-with-summary field-label-hidden"><!-- Warning Dialog Box -->
this is not visible

2024-11-21 16:44 UTC, Warrior1412 commented on node/3.html
> +    <div class="field field-name-body field-type-text-with-summary field-label-hidden"><!-- Warning Dialog Box -->
Yes, it was because of "display: none".

2024-11-21 16:45 UTC, Warrior1412 commented
Addressed the comments and committed again. Please check it, if possible.

2024-11-21 17:18 UTC, jdamerow commented
When you reopen the PR, it is automatically deployed and you can check (the link to the deployment is on the PR timeline)

2024-11-21 20:09 UTC, jdamerow commented
Ok, one last thing I think, that I didn't notice before:
- https://digitalhps-org-pr-5.onrender.com/node/11.html: can you change the name to my name
- https://digitalhps-org-pr-5.onrender.com/node/9.html: can you change the email address to the digitalhps one.

Thanks!

2024-11-21 20:47 UTC, Warrior1412 commented
Done.

2024-11-22 13:51 UTC, merged